name: Deploy via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar lftp
        run: sudo apt-get install -y lftp

      - name: Deploy via FTP (lftp)
        run: |
          lftp -d -c "
            set ftp:ssl-allow no;
            set ftp:ssl-force no;
            set ftp:ssl-protect-data no;
            set net:max-retries 3;
            set net:reconnect-interval-base 5;
            set ftp:passive-mode yes;
            open -u '${{ secrets.USER }}','${{ secrets.PASS }}' '${{ secrets.HOST }}';
            mirror --reverse --delete --verbose \
              --exclude-glob .git \
              --exclude-glob .github \
              --exclude-glob README.md \
              ./ /;
          "
